apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-example-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-example-project
  template:
    metadata:
      labels:
        app: laravel-example-project
    spec:
      volumes:
        - name: logs
          emptyDir: {}
      containers:
        - name: laravel-k8s-example-nginx
          imagePullPolicy: Always
          image: ghcr.io/ramazantuf/laravel-k8s-example-nginx:latest
          resources:
            limits:
              cpu: 500m
              memory: 500M
          ports:
            - containerPort: 80
        - name: laravel-k8s-example-fpm
          imagePullPolicy: Always
          securityContext:
            runAsUser: 82
            readOnlyRootFilesystem: true
            fsGroup: 82
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/storage/logs
          image: ghcr.io/ramazantuf/laravel-k8s-example-fpm:latest
          resources:
            limits:
              cpu: 500m
              memory: 500M
          ports:
            - containerPort: 9000
