name: Deploy to Kubernetes with Helm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - name: Deploy using Helm
        run: |
          helm upgrade --install myapp ./chart/myapp \
            --namespace mynamespace \
            --create-namespace \
            --set image.repository=ghcr.io/ramazantuf/laravel-k8s-nginx \
            --set image.tag=${GITHUB_SHA::8}
