name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image Nginx
      run: docker build . --file resources/ops/docker/nginx/Dockerfile --tag ghcr.io/ramazantuf/laravel-k8s-nginx:latest
    - name: Build the Docker image Fpm
      run: |
        docker build . --file resources/ops/docker/fpm/Dockerfile --tag ghcr.io/ramazantuf/laravel-k8s-fpm:latest
        docker login --username ramazantuf --password ${{ secrets.GH_PAT }} ghcr.io
        docker push ghcr.io/ramazantuf/laravel-k8s-nginx:latest
        docker push ghcr.io/ramazantuf/laravel-k8s-fpm:latest
